baseURL = "https://freshpopo.github.io"
languageCode = "ko-kr"
title = "Hugo Test Blog"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Test 1"
    url = "/test1/"
    weight = 2

  [[menu.main]]
    name = "Test 2"
    url = "/test2/"
    weight = 3
